name: Pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Run unit tests and Code Coverage
       run: bash ./gradlew jacocoTestDebugUnitTestReport
     - name: Setup sonarqube
       uses: warchant/setup-sonar-scanner@v1
     - name: SonarCloud Scan
       run: sonar-scanner
         -Dsonar.login=${{ secrets.sonar_cloud_token }}
         -Dsonar.host.url=https://sonarcloud.io/
