name: Pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Run unit tests
       run: bash ./gradlew test
     - name: Run Code Coverage
       run: bash ./gradlew jacocoTestReport
     - name: SonarCloud Scan
       run: bash ./gradle sonarqube
